### PR TITLE
Fixed timezone tests

### PR DESCRIPTION
**Pull request by arjanmels**

### CODE REVIEW

**Comment by arjanmels** [comment]
@xvrh Not sure what the check error is about "Uncomitted changes", do you?

**Comment by xvrh** [comment]
@arjanmels it seems this is the download date from the readme (that is taken from a file `lastModifiedSync`) that was creating difference.
If you don't mind, I removed the download date entry from the README

**Comment by arjanmels** [comment]
Makes sense. We might want to do the same from common_locale_data.dart.

**Comment by xvrh** [comment]
Thanks for the fix 👍

**Pull request merged**
